# Generated by Django 4.2.7 on 2025-06-07 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='comment_count',
        ),
        migrations.RemoveField(
            model_name='song',
            name='rank',
        ),
        migrations.AddField(
            model_name='song',
            name='hot',
            field=models.IntegerField(default=0, verbose_name='热度'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(verbose_name='评论内容'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='like_count',
            field=models.IntegerField(default=0, verbose_name='点赞数'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='sentiment',
            field=models.FloatField(default=0.0, verbose_name='情感得分'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.song', verbose_name='所属歌曲'),
        ),
        migrations.AlterField(
            model_name='song',
            name='album',
            field=models.CharField(blank=True, max_length=128, verbose_name='专辑'),
        ),
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.CharField(max_length=128, verbose_name='歌手'),
        ),
        migrations.AlterField(
            model_name='song',
            name='name',
            field=models.CharField(max_length=128, verbose_name='歌名'),
        ),
        migrations.AlterField(
            model_name='song',
            name='song_id',
            field=models.CharField(max_length=32, unique=True, verbose_name='歌曲ID'),
        ),
    ]
