# Generated by Django 4.2.7 on 2025-06-07 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_remove_song_comment_count_remove_song_rank_song_hot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='toplist',
            field=models.CharField(default='热歌榜', max_length=32, verbose_name='榜单'),
        ),
    ]
